import { useEffect, useState } from 'react'

import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


const defaultEndpoint = 'https://rickandmortyapi.com/api/character'

export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint)
  const data = await res.json()

  return {
    props: {
      data
    }
  }
}

export default function Home({ data }) {
  const { info, results: defaultResults = [] } = data

  const [results, updateResults] = useState(defaultResults)

  const [page, updatePage] = useState({
    ...info,
    current: defaultEndpoint
  })

  const { current } = page

  useEffect(() => {
    if (current === defaultEndpoint)
      return

    async function request() {
      const res = await fetch(current)
      const nextData = await res.json()

      updatePage({
        current,
        ...nextData.info
      })

      if (!nextData.info?.prev) {
        updateResults(nextData.results)
        return
      }

      updateResults(prev => {
        return [
          ...prev,
          ...nextData.results
        ]
      })

    }

    request()
  }, [current])


  function handleLoadMore() {
    updatePage(prev => {
      return {
        ...prev,
        current: page?.next
      }
    })
  }

  function handleOnSubmit(e) {
    e.preventDefault()

    const { currentTarget = {} } = e
    const fields = Array.from(currentTarget?.elements)
    const fieldQuery = fields.find(field => field.name === 'query')

    const value = fieldQuery.value || ''

    const endpoint = `https://rickandmortyapi.com/api/character/?name=${value}`

    updatePage({
      current: endpoint
    })


  }




  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main>
        <h1 className={styles.title}>
          Wubba Lubba Dub Dub
        </h1>

        <p className={styles.description}>
          Rick and Morty Wiki
        </p>

        <div className={styles.container}>
          <form className={styles.search} onSubmit={handleOnSubmit}>
            <input name='query' type='search' />
            <button className={styles.button}>Search</button>
          </form>
        </div>

        <ul className={styles.grid}>
          {results.map(result => {
            const { id, name, image } = result

            return (
              <li key={id} className={styles.card}>
                <Link href='/character/[id]' as={`/character/${id}`}>
                  <a>
                    <h3>{name}</h3>
                    <Image
                      src={image}
                      alt={`${name} Thumb`}
                      width={300}
                      height={300}
                    />
                  </a>
                </Link>
              </li>
            )
          })}
        </ul>

        <div className={styles.container}>
          <button className={styles.button} onClick={handleLoadMore}>Load more</button>
        </div>

      </main>






    </div>
  )
}
