import Head from 'next/head'
import Link from 'next/link'
import styles from '../../../styles/Home.module.css'

const defaultEndpoint = 'https://rickandmortyapi.com/api/character'

export async function getServerSideProps({ query }) {
  const { id } = query
  const res = await fetch(`${defaultEndpoint}/${id}`)
  const data = await res.json()

  return {
    props: {
      data
    }
  }
}

export default function Character({ data }) {
  const { name, image, gender, location, origin, species, status } = data
  console.log(data)
  return (
    <div className={styles.container}>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main>
        <h1 className={styles.title}>
          {name}
        </h1>

        <div className={styles.container}>
          <div className={styles.profileImg}>
            <img src={image} alt={name} />
          </div>

          <div className={styles.profileDetails}>
            <h2 className={styles.description}>Character details</h2>
            <ul className={styles.detailsList}>
              <li>
                <strong>Name: </strong>{name}
              </li>
              <li>
                <strong>Status: </strong>{status}
              </li>
              <li>
                <strong>Gender: </strong>{gender}
              </li>
              <li>
                <strong>Species: </strong>{species}
              </li>
              <li>
                <strong>Location: </strong>{location?.name}
              </li>
              <li>
                <strong>Origin: </strong>{origin?.name}
              </li>
              <li>
                <strong>Status: </strong>{status}
              </li>
            </ul>
          </div>
        </div>

        <p className={styles.goBack}>
          <Link href='/'>
            <button className={styles.button}>Back to all characters</button>
          </Link>
        </p>

      </main>






    </div>
  )
}
